import type { Metadata } from "next";
import "./globals.css";
import { lora, inter } from "@/configs/fonts";
import ThemeProvider from "@/providers/ThemeProvider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "To Do List task for testing",
  description: "Generated by create next app with SXNPAII",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lora.variable}`}>
        <ThemeProvider>
          <main className={cn(`h-screen px-3 sm:px-5 xl:px-10 py-3 `)}>
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
